### ISSUE TITLE
Let me help you.

### ISSUE THREAD

**Issue by 4ck1rman** [bgbing/Matchman#14]
I'll be helping out the Matchmaker security team by attacking the TOOLS forum. I actually despise the fly-by-night nature of the TOOLS forums. But before I attack, I have a request . please let me can can need new new

**Comment by gh0sthzr** [comment]
new new too small

**Comment by d-rn** [comment]
tiny new new

**Comment by qiangdaoqiang** [comment]
okok,gogogo

**Comment by bigmatchstick** [comment]
翻译：我可以帮助火柴人，在此之前有个请求，请先展示一下你的技能。 @bgbing
