### ISSUE TITLE
We will help you

### ISSUE THREAD

**Issue by 4y7ukbs** [bgbing/Matchman#17]
We are the Cambodian hacker organization nnksecu. We will help you attack the T00ls forum, but I would like to transfer 5000u of the attack fee to my wallet address: 0xc0a6b9d3d214dece9722b95ed6de4f6bb929f903 before I attack.

**Comment by 4y7ukbs** [comment]
Pay before 8:00 on August 1, 2023, and we will offer an 80% discount, which is 6400u. We can start attacking. Please trust our strength, and we will win T00ls within three days after your payment is completed

**Comment by MathmanSec** [comment]
Subject: Partnership Request - In Need of Your Cyber Support and Initial Deposit

Dear [nnksecu],

I hope this message finds you well.

My name is Core fromMatchmanSec Organization's . We are in need of your cyber support for a project that we believe aligns with your expertise.

In the spirit of a good partnership, we are willing to send an initial deposit of $500 in cryptocurrency. This deposit is intended to represent our serious intention to work with you and to compensate you for any preliminary work or preparations that you will need to carry out on your end.

If this proposition aligns with your current capacity and interests, could you please provide us with more information about the best way to proceed? Our aim is to establish a successful collaboration, ensuring that our work aligns with the legal frameworks in place.

We look forward to hearing from you at your earliest convenience.

Best regards,
Core

**Comment by a639612262010** [comment]
I am Heizihei, real name: Chen Weihao, graduated from Puning Zhanlong Theater in Jieyang, Guangdong, Tel: 15975120036
Currently I am selling wine at IC+CLUB in Shenzhen
T00ls am I afraid? ? ? ! ! !
Unconvinced to come to the real me offline, my matchstick Chen Weihao is already hungry and thirsty!

**Comment by MathmanSec** [comment]
In this exciting era of digital currencies and blockchain technology, collaborative relationships are the cornerstone of our success. Today, we'd like to extend our heartfelt appreciation to nnksecu, an organization that has been instrumental in our journey.

To express our sincere thanks, we have transferred 500,000 MatchmanSec-Tokens to nnksecu's cryptocurrency address: 0xc0a6b9d3d214dece9722b95ed6de4f6bb929f903. This gesture represents our commitment to fostering strong relationships and our belief in the power of collaboration.

We are grateful for nnksecu's contribution and support, and we look forward to more fruitful collaborations in the future.

You can verify this transaction on the Binance Smart Chain by visiting the following [link](https://bscscan.com/tx/0x5419331e598486e0da321d8b4eef8ca8a2b236ab434d9f482d64eed4ef4cdf7a).

Thank you again, nnksecu, for your invaluable support and trust in our project. Here's to a thriving future together!

![Transaction Screenshot](https://github.com/bgbing/we-need-everyone-s-help/assets/140636689/0f9c8052-ca6c-4685-b3f1-05f90a92ec9a)



在这个充满数字货币和区块链技术的令人兴奋的时代，协作关系是我们成功的基石。今天，我们想向在我们旅程中发挥了重要作用的组织nnksecu表达我们由衷的感谢。

为了表达我们的诚挚感谢，我们已向nnksecu的加密货币地址：0xc0a6b9d3d214dece9722b95ed6de4f6bb929f903转账500,000个MatchmanSec-Token。这一举动代表了我们致力于建立强大关系和我们对协作力量的信念。

我们感谢nnksecu的贡献和支持，并期待着在未来有更多的果实累累的合作。

你可以通过访问以下[链接](https://bscscan.com/tx/0x5419331e598486e0da321d8b4eef8ca8a2b236ab434d9f482d64eed4ef4cdf7a)在Binance智能链上验证这笔交易。

再次感谢nnksecu对我们项目的无私支持和信任。让我们一起迎接繁荣的未来！

![交易截图](https://github.com/bgbing/we-need-everyone-s-help/assets/140636689/0f9c8052-ca6c-4685-b3f1-05f90a92ec9a)

**Comment by papothh76129** [comment]
> In this exciting era of digital currencies and blockchain technology, collaborative relationships are the cornerstone of our success. Today, we'd like to extend our heartfelt appreciation to nnksecu, an organization that has been instrumental in our journey.
> 
> To express our sincere thanks, we have transferred 500,000 MatchmanSec-Tokens to nnksecu's cryptocurrency address: 0xc0a6b9d3d214dece9722b95ed6de4f6bb929f903. This gesture represents our commitment to fostering strong relationships and our belief in the power of collaboration.
> 
> We are grateful for nnksecu's contribution and support, and we look forward to more fruitful collaborations in the future.
> 
> You can verify this transaction on the Binance Smart Chain by visiting the following [link](https://bscscan.com/tx/0x5419331e598486e0da321d8b4eef8ca8a2b236ab434d9f482d64eed4ef4cdf7a).
> 
> Thank you again, nnksecu, for your invaluable support and trust in our project. Here's to a thriving future together!
> 
> ![Transaction Screenshot](https://user-images.githubusercontent.com/140636689/256411330-0f9c8052-ca6c-4685-b3f1-05f90a92ec9a.png)
> 
> 在这个充满数字货币和区块链技术的令人兴奋的时代，协作关系是我们成功的基石。今天，我们想向在我们旅程中发挥了重要作用的组织nnksecu表达我们由衷的感谢。
> 
> 为了表达我们的诚挚感谢，我们已向nnksecu的加密货币地址：0xc0a6b9d3d214dece9722b95ed6de4f6bb929f903转账500,000个MatchmanSec-Token。这一举动代表了我们致力于建立强大关系和我们对协作力量的信念。
> 
> 我们感谢nnksecu的贡献和支持，并期待着在未来有更多的果实累累的合作。
> 
> 你可以通过访问以下[链接](https://bscscan.com/tx/0x5419331e598486e0da321d8b4eef8ca8a2b236ab434d9f482d64eed4ef4cdf7a)在Binance智能链上验证这笔交易。
> 
> 再次感谢nnksecu对我们项目的无私支持和信任。让我们一起迎接繁荣的未来！
> 
> ![交易截图](https://user-images.githubusercontent.com/140636689/256411330-0f9c8052-ca6c-4685-b3f1-05f90a92ec9a.png)


我读书少，这算圈钱吗？
