### ISSUE TITLE
来看陈伟豪的身份证和住址还有证件照啦，傻逼露脸了！！！

### ISSUE THREAD

**Issue by a1catrazz** [bgbing/Matchman#28]
来，傻逼，看看自己那逼样！

<img width="640" alt="我是傻逼陈伟豪" src="https://github.com/bgbing/we-need-everyone-s-help/assets/98398055/dabd13be-87d7-4b27-a003-59a05d966aa1">

**Comment by a639612262010** [comment]
陈伟豪，广东揭阳普宁占陇戏院毕业，电话：15975120036
目前在深圳IC+CLUB卖酒

**Comment by Un1C0RNSSRS** [comment]
这码等于没打🤭
