### ISSUE TITLE
我陈伟豪，怕你们？？？

### ISSUE THREAD

**Issue by a639612262010** [bgbing/Matchman#4]
我是黑子黑，真名：陈伟豪，广东揭阳普宁占陇戏院毕业，电话：15975120036
目前我在深圳IC+CLUB卖酒
T00ls我会怕？？？！！！
不服来线下真实我，我陈伟豪的火柴棍已经饥渴难耐

**Comment by athenahk** [comment]
哈哈哈,和别人聊天拍自己的吊,笑死

**Comment by nanchen737491213** [comment]
孤儿东西 操你妈逼的 你妈死了是吧

**Comment by a639612262010** [comment]
不服来干我陈伟豪，一群小垃圾
![fee110b5733cb4482da32eb02f568a1](https://github.com/bgbing/we-need-everyone-s-help/assets/61104521/719bdc93-85c9-492a-8e9e-3f30cc0b219a)
